version: '2'

services:
  process:
    image: alfresco/process-services:1.6.2
    environment:
      ACTIVITI_DATASOURCE_USERNAME: alfresco
      ACTIVITI_DATASOURCE_PASSWORD: alfresco
      ACTIVITI_DATASOURCE_DRIVER: org.postgresql.Driver
      ACTIVITI_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      ACTIVITI_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/activiti?characterEncoding=UTF-8'
      ACTIVITI_CSRF_DISABLED: 'true'
      ACTIVITI_CORS_ENABLED: 'true'
      ACTIVITI_ES_SERVER_TYPE: client
      ACTIVITI_ES_DISCOVERY_HOSTS: elasticsearch:9300
      ACTIVITI_ES_CLUSTER_NAME: elasticsearch
    volumes:
        #- ./aps-config/enterprise-license:/root/.activiti/enterprise-license/:ro
        #- ./aps-config:/usr/share/tomcat/lib/
        #- ./aps-config/transform.lic:/usr/share/tomcat/lib/transform.lic
        - ./aps-data/process:/usr/local/data/
    ports:
    - 9999:8080
    links:
      - elasticsearch:elasticsearch
      - postgres-aps:postgres-aps
    depends_on:
      - elasticsearch
      - postgres-aps

  elasticsearch:
    image: elasticsearch:1.7.3
  postgres-aps:
    image: postgres:9.6.2
    environment:
      POSTGRES_DB: activiti
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    volumes:
        - ./aps-data/postgres:/var/lib/postgresql/data
